### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by BookOwl** [liam4/programming-language-thing#4]
```
    code: function(...args) {
                   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I'm running Node 5.3.0

**Comment by towerofnix** [comment]
oops, forgot to add flags to the README!

Will fix.
